jobs:

# jobs for the box demo pipelines from CI thru TEST environment

################################

# # CI for VISUALIZER
#   - name: prod-yml-sync
#     type: rSync
#     steps:
#       - IN: prod-deploy

# add visualizer pipeline workflow for CI
# VISUALIZER JOBS - test environment

# CI for VISUALIZER
# note: for demo purposes only, do not use
  - name: dv-ci
    type: runCI
    steps:
      - IN: dv-repo
      - TASK: managed
      - OUT: dv-img

# add visualizer pipeline workflow thru hub

# manifest gen for VISUALIZER
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-img
      - IN: dv-img-opts
      - IN: trigger-test-deploy-dv
      - TASK: managed

# deploy visualizer to TEST

# # TEST deployment for VISUALIZER to Amazon ECS
#   - name: dv-test-ecs
#     type: deploy
#     steps:
#       - IN: dv-man
#       - IN: dv-params
#         applyTo: dv-img
#       - IN: trigger-test-deploy-dv
#       - IN: env-test-ecs
# #       - IN: env-test-triton
#       - TASK: managed

# TEST deployment for VISUALIZER to Joyent Triton
  - name: dv-test-triton
    type: deploy
    steps:
      - IN: dv-man
      - IN: dv-params
        applyTo: dv-img
      - IN: env-test-triton
      - IN: trigger-test-deploy-dv
      - TASK: managed

# ################################

# BOX JOBS - test environment
# 4b) add BOX pipeline workflow for CI thru TEST
# CI for BOX
  - name: box-ci
    type: runCI
    steps:
      - IN: box-repo
      - TASK: managed
      - OUT: box-img

# manifest gen for BOX
  - name: box-man
    type: manifest
    steps:
      - IN: box-img
      - IN: box-img-opts
      - TASK: managed

# # TEST deployment for BOX to Amazon ECS
#   - name: box-test-ecs
#     type: deploy
#     steps:
#       - IN: box-man
#       - IN: box-t-params
#       - IN: trigger-test-deploy-box
#       - IN: env-test-ecs
#       - IN: box-t-ecs-params
#       - TASK: managed
#         deployMethod: upgrade

# # TEST deployment for BOX to Amazon ECS
#   - name: box-test-triton
#     type: deploy
#     steps:
#       - IN: box-man
#       - IN: box-t-params
#       - IN: box-t-tpc-params
#       - IN: trigger-test-deploy-box
#       - TASK: managed
#         deployMethod: upgrade


# ################################

# # increment release version
#   - name: demo-rel
#     type: release
#     steps:
#       - IN: demo-ver
#       - IN: box-test-ecs
#         trigger: true
#       - IN: dv-test-ecs
#         trigger: true
#       - TASK: managed
#         bump: patch

# ################################

# # execute custom script
#   - name: execute-sample-script
#     type: runSh
#     steps:
#       - IN: custom-script-repo
#       - IN: box-test-aws-ecs
#       - TASK:
#         - script: ./custom_script.sh

# ################################
