triggers:
  - name: trigger-test-deploy-dv
    type: trigger
    version:
      message: 'testing trigger in test 2'

  - name: trigger-test-deploy-box
    type: trigger
    version:
      counter: 10
